name:                html-render
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  html-render-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - html-render
    - bytestring
    - parsec
    - network
    - http-client
    - http-types

# tests:
#   html-render-test:
#     main:                Spec.hs
#     source-dirs:         test
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - sampleStack
